sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
services:
  - docker
node_js:
  - '8'

env:
  - DEBUG=*
before_install:
  - sudo apt-get update

before_script:
  - npm prune

script:
  - npm run build
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release